# Settings

# Colors:
#   BLACK = &0, DARK_BLUE = &1, DARK_GREEN = &2, DARK_AQUA = &3
#   DARK_RED = &4, DARK_PURPLE = &5, GOLD = &6, GRAY = &7
#   DARK_GRAY = &8, BLUE = &9, GREEN = &a, AQUA = &b
#   RED = &c, LIGHT_PURPLE = &d, YELLOW = &e, WHITE = &f

# Formats:
#   OBFUSCATED = &k, BOLD = &l, STRIKETHROUGH = &m,
#   UNDERLINE = &n, ITALIC = &o, RESET = &r


# 0 for everyone, 1 for specific players
mode: 1

# 1 unit = 1 tick
run-after: 20

# string for title
title: ""

# string for subtitle
subtitle: "&l恭喜老哥房子沒啦!"

# 1 unit = 1 tick
title-fade-in: 2

# 1 unit = 1 tick
title-stay: 40

# 1 unit = 1 tick
title-fade-out: 2

# player's name
players:
  - "PurpleLight_PVP"